### ISSUE TITLE
[1.19.0] Game crashes, not on startup but when opening world.

### ISSUE THREAD

**Issue by craftnightasdfasdf** [kwpugh/easy_emerald_forge#11]
This is the error i get

(https://github.com/kwpugh/EasyEmerald/files/9126739/crash-2022-07-16_19.04.21-server.txt)

**Comment by craftnightasdfasdf** [comment]
P,S this only happens when I add Easy emerald without it the world loads up fine.

**Comment by craftnightasdfasdf** [comment]
I just tried removing every other mod and it still shows the error.

**Comment by kwpugh** [comment]
There  was a breaking change after 41.0.63, so either update forge  to latest 41.0.99 or use easy emerald v1.4.0

**Comment by kwpugh** [comment]
Guessing you can't update too latest Forge
<img width="762" alt="Screen Shot 2022-07-16 at 6 52 36 PM" src="https://user-images.githubusercontent.com/8809210/179375395-0b6bb19a-3513-4f5f-9c11-2458936086df.png">

so best to downgrade Easy Emerald

**Comment by craftnightasdfasdf** [comment]
Thank you that worked!
