### ISSUE TITLE
[1.19 and 1.19.1] registry object not present

### ISSUE THREAD

**Issue by nyancatkitty** [kwpugh/easy_emerald_forge#12]
i got this error when trying to load the mod, and i've tried to do both 1.19 and 1.19.1 versions of this mod, the error is: Easy Emerald (easy_emerald) encountered an error during the sided_setup   java.lang.NullPointerException:  Registry Object not present: easy_emerald:emerald_bow

this is a picture of the error
![Screenshot (861)](https://user-images.githubusercontent.com/110431467/182259775-a9f64ad4-0458-4777-a340-e809cf20edb4.png)

is there somehow it can be fixed?

**Comment by kwpugh** [comment]
did you disable the  bow some how with kubeJs or something?   no idea how else that can happen.

**Comment by nyancatkitty** [comment]
> did you disable the bow some how with kubeJs or something? no idea how else that can happen.

i dont know, and i just tried removing the fabric mods i also had in the mods folder (cause i do use both fabric and forge) and what is werid for me through, the fabric one works fine cause right now im trying to use forge so i could use  biomes o plenty mod (and its still the same when i removed the fabric mods in the mods folder)

**Comment by kwpugh** [comment]
you shouldn't mix forge and fabric mods in the same folder.  make separate modpack

can you post the crash report for when it last crashed?

**Comment by nyancatkitty** [comment]
> you shouldn't mix forge and fabric mods in the same folder. make separate modpack
> 
> can you post the crash report for when it last crashed?


![Screenshot (862)](https://user-images.githubusercontent.com/110431467/182267415-01b79c32-f172-4842-a940-a767a0faf11d.png)
![Screenshot (863)](https://user-images.githubusercontent.com/110431467/182267417-9f978d05-17ce-4019-89fd-de00e627fc1b.png)
![Screenshot (864)](https://user-images.githubusercontent.com/110431467/182267420-db45dbd7-fdcf-4eef-9525-9862e656e679.png)

this was the crash report i just got right now, and these was all of the mods that are still in the mods folder right now 
![Screenshot (866)](https://user-images.githubusercontent.com/110431467/182267907-eff7ffa4-f01a-4914-a7e9-5672a13b0d00.png)

**Comment by kwpugh** [comment]
if you are running 1.19.1 you should be using [EasyEmerald-Forge-1.19.1-1.4.2.jar](https://www.curseforge.com/minecraft/mc-mods/easy-emerald-tools/files/3905045)

**Comment by nyancatkitty** [comment]
> if you are running 1.19.1 you should be using [EasyEmerald-Forge-1.19.1-1.4.2.jar](https://www.curseforge.com/minecraft/mc-mods/easy-emerald-tools/files/3905045)

i put that version in the mods folder and it still shows the same error

**Comment by kwpugh** [comment]
post a copy of the latest.log after you run with the v1.4.2

**Comment by kwpugh** [comment]
I think it is BoP and TerraBlender.  Try without.

Those two crash my modpack.

**Comment by nyancatkitty** [comment]
> 



> I think it is BoP and TerraBlender. Try without.
> 
> Those two crash my modpack.

i just tried and it did work, but thing that does suck for me is that i did wanted to use the biomes o plenty mod cause of the like  certain cherry blossom like trees the mod has in it

**Comment by kwpugh** [comment]
Perhaps it will work when BoP updates to 1.19.1.

**Comment by kwpugh** [comment]
It must be some other factor.  I setup a fresh world with BoP and Emerald Tools, and it runs fine.

**Comment by kwpugh** [comment]
went in a second time and boom, crashed.

**Comment by kwpugh** [comment]
What version of Forge are you running?

https://github.com/Glitchfiend/BiomesOPlenty/issues/2032

**Comment by kwpugh** [comment]
This is not an issue for me to fix
