### ISSUE TITLE
[1.19.2] 3x3 Tools Dont break 

### ISSUE THREAD

**Issue by Daihok41** [kwpugh/easy_emerald_forge#14]
3x3 tools arent breaking when they hit 0 durability. I have config set for 3x3 tools to take full damage. I tested with copper hammer several times.

**Comment by kwpugh** [comment]
LOL, fix one issue and create another.  I think I know why that happens, because of the logic to take full damage.

**Comment by kwpugh** [comment]
pushing v12 to curse forge, I think I got it this time.

**Comment by kwpugh** [comment]
https://www.curseforge.com/minecraft/mc-mods/easy-emerald-tools/files/3994580

**Comment by kwpugh** [comment]
fixed  in v12
