### ISSUE TITLE
Armor equip disconnecting other players

### ISSUE THREAD

**Issue by veeone-ops** [kwpugh/easy_emerald_forge#15]
Equipping any of the mod's armors causes a crash/disconnect for other players
![image](https://user-images.githubusercontent.com/103021837/194692101-23a49447-1358-46b7-aa44-9535b1f7e541.png)

**Comment by kwpugh** [comment]
do  you have game log I can see?  I don't think that is my mod, but I  can't tell much from just that  message.

**Comment by kwpugh** [comment]
1.18.2   or 1.19.2?

**Comment by kwpugh** [comment]
Lack of information, closed.
