### ISSUE TITLE
[1.19.2] Bow Issue with shield

### ISSUE THREAD

**Issue by someonedeepintheinternet** [kwpugh/easy_emerald_forge#16]
if you hold block with a shield(left hand) and swap to the bow(right hand), it still zooms in, even without arrows.

**Comment by kwpugh** [comment]
zoom is part of the bow, not the arrows
 its kind of handy

**Comment by kwpugh** [comment]
I tried that it does not work.

shield in offhand, press and hold right-mouse button to hold up shield to block
and have an emerald bow in mainhand... shield and bow just switch, no zoom

with an arrow in inventory, the bow will zoom with the arrow and when swap, zoom ends

what am I missing.

**Comment by kwpugh** [comment]
![bow_clip](https://user-images.githubusercontent.com/8809210/197271451-7c6344d1-0b83-43a4-8e8f-36201800f0c2.gif)

**Comment by Somebody139** [comment]
So you block first with the shield(left hand) and then right click hold the bow with the right hand, without arrows or creative mode. If it obly appears to me i can send a video of it happening

**Comment by kwpugh** [comment]
I tried with and without an arrow in inventory in survival, zoom releases when swap bow and shield.

**Comment by someonedeepintheinternet** [comment]
try it with block first and hold the block, without any arrows in inventory and right hand bow
![Bow_issue](https://user-images.githubusercontent.com/116382854/197310018-2c7b9e12-3b5a-4f0c-9b9b-441bb15807a9.gif)
thats what i meant

**Comment by kwpugh** [comment]
I got it.  I had to have something other than the bow in the mainhand and switch to it when blocking with the shield

**Comment by someonedeepintheinternet** [comment]
Do you think you can fix it? Wish ya good luck

**Comment by kwpugh** [comment]
Already fixed.

**Comment by someonedeepintheinternet** [comment]
Wha.. really? Is there now a updated version already? Aight i will close the issue

**Comment by kwpugh** [comment]
I will push out an update shortly

Thanks for letting me know.
