### ISSUE TITLE
[1.19.2] Bow issue with shield 2.0

### ISSUE THREAD

**Issue by someonedeepintheinternet** [kwpugh/easy_emerald_forge#17]
So the issue got solved at first. not trying to be a dck, **but the issue is still there but when you have a arrow in the inventory**. Without the arrow it works fine. Sorry mate

**Comment by kwpugh** [comment]
I just noticed this in testing.  This may not be fixable with the forge event though.

What problem is this causing in your game play?

**Comment by kwpugh** [comment]
I think the only way to solve this is to require that the off hand is empty when using the bow in main hand with zoom

I'm not sure that is a better situation

**Comment by someonedeepintheinternet** [comment]
Well that sucks but its not that dramatic in my opinion. I can live with that. I thought you coded it like a usual minecraft bow.

**Comment by kwpugh** [comment]
Minecraft vanilla code does not expose the built in zoom, so I wrote a custom zoom with the side benefit being to set the zoom factor for the bow in the mod's config

**Comment by kwpugh** [comment]
I think I would rather give them the zoom while blocking with a shield rather than leaving them scratching their head as to why now zoom on the bow, when there is something in their off hand.

**Comment by someonedeepintheinternet** [comment]
did you try to look into other mods that include a bow? Maybe they solved the issue already(kind of). Can't help ya much with coding, never learned it in any way.

**Comment by kwpugh** [comment]
I had, but the level of their code complexity was beyond me.

To be totally honest, my forge mods are mostly in maintenance mode.  My primary efforts going forward will be on Fabric and Quilt.  1.19.2 or 1.19.3 or likely the last version I will be supporting them.

That said, I'm not willing to expend a lot of effort chasing this down.  My fabric bows use similar code but the Fabric API doesn't seem to have this quirk.

**Comment by someonedeepintheinternet** [comment]
alright, as i said, i can live with the small bug. Its your mod, your rules and doings. The mod itself is good enough. Shall i close the issue or let it open?
