### ISSUE TITLE
server kicks me after I put modded armor on armor stand

### ISSUE THREAD

**Issue by BlackDogTM** [kwpugh/easy_emerald_forge#19]
Hey there,

I encountered an issue with the armor stand. If I put any of the modded armor pieces from this mod on an armor stand, it kicks me with a notification related to a sound. 

Can you tell me how to fix this?

![2022-11-12_13 56 18](https://user-images.githubusercontent.com/118056384/201475054-ed7d34b0-868b-4d30-b0d5-01dd25bd1303.png)

**Comment by kwpugh** [comment]
which version of the mod are you using?

are you using a mod that alters/replaces the vanilla armor stand?

**Comment by BlackDogTM** [comment]
I'm using EasyEmerald-Forge-1.19.2-1.4.14 on Forge 43.1.10

and no, there's no such mod that alters the vanilla armor stand

**Comment by kwpugh** [comment]
I cannot replicate by itself.  What other mods are you using, if any?

**Comment by kwpugh** [comment]
also, please post a copy of your system  log.

**Comment by kwpugh** [comment]
NEvermind, I was able to replicate on my test server.  It seems mojang changed how sound events are returned from server.  I know how to fix.

**Comment by kwpugh** [comment]
Gobber mod was fine, but Emerald Tools, Easy Steel and Powder Power need fixing.

**Comment by kwpugh** [comment]
I just published a new v15 of Emerald Tools on Curseforge, should approve shortly.

**Comment by kwpugh** [comment]
let  me know if you  have  any other issues.

**Comment by BlackDogTM** [comment]
great, thank you so much for your fast response! Everything is working as it should. :)
