### ISSUE TITLE
Excavator, Hammer, Paxel, and Tree axe (1.16.5)

### ISSUE THREAD

**Issue by Diamonda101** [kwpugh/easy_emerald_forge#20]
![image](https://user-images.githubusercontent.com/76970218/202890105-ac2a2412-e621-4f48-a718-54dc9b1b9098.png)

![image](https://user-images.githubusercontent.com/76970218/202889986-9a18cb81-b491-40f1-9be1-02ee90eb11a5.png)

The first one is from the mod page and the last one is from my game.where is the wood, stone, iron, gold, diamond, natherite. 
Can this be added or fixed plzz

**Comment by kwpugh** [comment]
those are in 1.19.2+

**Comment by Diamonda101** [comment]
> those are in 1.19.2+

could you update it so its in 1.16.5 too

**Comment by kwpugh** [comment]
I do not back port new features
