### ISSUE TITLE
Hammers not losing durability on 3x3 mine

### ISSUE THREAD

**Issue by percyV13** [kwpugh/easy_emerald_forge#22]
I'm using the most recent version of Emerald Tools, plus a number of other mods though I don't think any should be messing with tools.

When mining your standard 3x3 area with a hammer it doesn't lose any durability. Shift-mining a single block does lose durability as expected. I've tried with wood, copper, and amethyst hammers so far to the same effect. The other tools lose durability as expected, it's just the hammers when mining 3x3.

When I get home I can post a list of the mods in use if needed.

**Comment by kwpugh** [comment]
Sorry for the late reply here.

I tried Emerald Tools Forge 1.19.2 and 1.20.1 plus NeoForge 1.20.4 versions and all hammers take damage.

Let me know if this is still happening otherwise I will consider this closed.
