### ISSUE TITLE
Can't make bows. 

### ISSUE THREAD

**Issue by KTSilence** [kwpugh/easy_emerald_forge#29]
On the mod page it lists that the bows are made with the smithing table but after going to my smithing table in game there is only spots for templates and ores to upgrade armor, weapons etc. How are the bows supposed to be made? (ver. 1.20.1

**Comment by someonedeepintheinternet** [comment]
isn't the mod not updated to 1.20.x? 1.20.x isn't out officially yet (I think), since it doesn't get shown on curseforge. just wait a bit I guess. on the 1.20 update the GUI changed for the smithing table, so hes probably working on it.

**Comment by kwpugh** [comment]
1.19.3 isn't likely to work in 1.20 due to so many changes.  I will be updating the mod to 1.20.x at some point.

**Comment by kwpugh** [comment]
fixed in 1.20.1 update
