### ISSUE TITLE
[Enhancement] Translations for 1.20.1 versions

### ISSUE THREAD

**Issue by mpustovoi** [kwpugh/easy_emerald_forge#34]
I just added translations for the 1.20.1 versions of the mod, although the fork was from 1.19.2, since there is no branch for 1.20.1.
However, you can still add a file with translations not directly.

**Comment by mpustovoi** [comment]
https://github.com/kwpugh/easy_emerald_forge/pull/33

**Comment by kwpugh** [comment]
added to upcoming update
