### ISSUE TITLE
[Enhancement] Remove config limitations

### ISSUE THREAD

**Issue by mpustovoi** [kwpugh/easy_emerald_forge#38]
In the Fabric version, there are no restrictions on setting values, for example, the mining speed of items. The Forge version has them.
For example, I want to make obsidian items more effective than diamond ones, but I can't do it because of the `7.0` limitation for mining speed, while diamond efficiency is `8.0`. Same thing for setting durability, for example, for copper less than `200`.
Is there a way to lose these restrictions? I don't think this is related to the features of the Forge loader, because some mods have tools with efficiency up to `10` and maybe even more.

**Comment by kwpugh** [comment]
which version are you using?

**Comment by mpustovoi** [comment]
I'm using `EasyEmerald-Forge-1.20.1-1.5.7`
So if I set `10.0` here in config, when I launch the game, the value goes back to `7.0` cap:
```
	#Obsidian Tool efficiency [1.0-7.0, default: 5.5]
	#Range: 0.0 ~ 7.0
	obsidianToolEfficiency = 7.0
```

**Comment by kwpugh** [comment]
yeah, I will have to change the limit in the config builder.

**Comment by mpustovoi** [comment]
Looking forward to it

**Comment by kwpugh** [comment]
I'm setting the new limit at 15

**Comment by kwpugh** [comment]
Keep in mind, obsidian will still have a mining level of iron

**Comment by mpustovoi** [comment]
Thanks. That even makes sense for me.
I suppose the mining level cannot be determined through the config, since this results the whole new method addition for all tools.

**Comment by kwpugh** [comment]
Published a new version to curseforge
