### ISSUE TITLE
[1.17.1] mod makes netherite equipment unobtainable in survival

### ISSUE THREAD

**Issue by KrystalTheFox** [kwpugh/easy_emerald_forge#4]
Hey. while I was using this mod, i went to go make netherite armor, but when I try to make netherite armor in the smithing table with diamond gear, it does not work. it just shows a red X like the item doesnt exist

**Comment by kwpugh** [comment]
Can you show a screenshot please?

What version of the mod are you using?

**Comment by kwpugh** [comment]
Are you referring to this?

![Screen Shot 2021-07-30 at 2 07 38 PM](https://user-images.githubusercontent.com/8809210/127700616-a617dc74-ca1b-4af2-a9a2-0b85f364b903.png)
![Screen Shot 2021-07-30 at 2 07 48 PM](https://user-images.githubusercontent.com/8809210/127700618-5d4e071b-a57a-434d-bb8a-c86ca549ae68.png)

**Comment by kwpugh** [comment]
Tested this in both 1.16.5 and 1.17.1 and it works fine.  If I am misunderstanding the issue, please let me know, otherwise I will close this issue.

**Comment by kwpugh** [comment]
Lack of information, my testing showed fine.
