### ISSUE TITLE
The full set bonus config option doesn't do anything

### ISSUE THREAD

**Issue by Shadowglitchjpg** [kwpugh/easy_emerald_forge#41]
Mod version - 1.6.22 for NeoForge.
While editing the mod config, I noticed that you can enable full set bonuses for armor. I set all of the full_set_bonus parameters to "true" and reloaded the game. When I re-equipped the amethyst armor set I had and jumped from a cliff, I still took fall damage.

**Comment by kwpugh** [comment]
I see the problem.  I will get an update in a little bit.

**Comment by kwpugh** [comment]
it affected all three sets.

**Comment by kwpugh** [comment]
version 1.6.28 has been pushed to cursweforge and fixes this issue.
