### ISSUE TITLE
Can't make bows. 1.21.1

### ISSUE THREAD

**Issue by TheGoodReverend** [kwpugh/easy_emerald_forge#43]
https://github.com/kwpugh/easy_emerald_forge/issues/29

Appears to be same issue as #29.  

Unable to upgrade bows in smithing table.  

![image](https://github.com/user-attachments/assets/7ecb58f8-2740-4dc6-bbdf-7faadbd9801b)

**Comment by TheGoodReverend** [comment]
Please let me know if I'm just using it incorrectly.

**Comment by kwpugh** [comment]
You need to use a Bow Smithing Template

![Screenshot 2024-08-26 at 2 31 23 PM](https://github.com/user-attachments/assets/b3b9036d-a814-4dee-b84d-6acd7b2682c4)
