### ISSUE TITLE
can't craft emerald tools?

### ISSUE THREAD

**Issue by louisdoran1234** [kwpugh/easy_emerald_forge#7]
I can't craft emerald tools and when I use the JEI menu there are no recipes for the emerald tools and the emeralds can't craft them

**Comment by kwpugh** [comment]
What version of Easy Emerald are you using?  What version of Forge are you using?

**Comment by louisdoran1234** [comment]
my bad it was for the EmeraldTools mod xd

**Comment by kwpugh** [comment]
Also, post a link to your latest log.

**Comment by louisdoran1234** [comment]
dw man i got my mods confused

**Comment by kwpugh** [comment]
ah, no problem.

You might try mine, it has recipes, LoL
